apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${SERVICE_NAME}
  name: ${SERVICE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - name: ${SERVICE_NAME}
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NAME}
        ports:
          - containerPort: ${APP_PORT}
        env:
        - name: APP_PORT
          value: "${APP_PORT}"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key:  dbusername
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key:  dbpass
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: credentials
              key:  aline-host
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key:  dbname
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key:  secret-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key:  jwt-secret-key
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
      restartPolicy: Always

